CREATE TABLE SATICI(
SATICIID INTEGER IDENTITY(1,1) NOT NULL,
SATICIADI VARCHAR(20) NOT NULL,
SATICISOYADI VARCHAR(20) NOT NULL,
SATICITELEFON VARCHAR(11) NOT NULL
PRIMARY KEY CLUSTERED 
 (
	SATICIID ASC
 )WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY] 
)ON [PRIMARY]


CREATE TABLE URUN(
URUNID INTEGER IDENTITY(1,1) NOT NULL,
URUNKODU VARCHAR(20) NOT NULL,
URUNADI VARCHAR(20) NOT NULL,
URUNFİYATI MONEY,
PRIMARY KEY CLUSTERED 
 (
	URUNID ASC
 ) WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY] 
) ON [PRIMARY]




CREATE TABLE SIPARIS(
SIPARISID INTEGER IDENTITY(1,1) NOT NULL,
MUSTERIID INTEGER,
SIPARISTARIH VARCHAR(10),
SIPARISDURUM VARCHAR(20),
URUNID INTEGER,
SATICIID INTEGER,
PRIMARY KEY CLUSTERED 
 (
	SIPARISID ASC
 ) WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY] 
) ON [PRIMARY]



CREATE TABLE ADRES(
ADRESID INTEGER IDENTITY(1,1),
MusterıID INTEGER,
ADRESULKE VARCHAR(25) NOT NULL,
ADRESIL VARCHAR(25) NOT NULL,
ADRESILCE VARCHAR(25)NOT NULL,
ADRESYORUM VARCHAR(100) NOT NULL
PRIMARY KEY CLUSTERED 
 (
	ADRESID ASC
 )  WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY] 
)ON [PRIMARY]


CREATE TABLE MUSTERILER(
MUSTERIID INT IDENTITY(1,1) NOT NULL,
MUSTERIAD VARCHAR(20) NOT NULL,
MUSTERISOYAD VARCHAR(20) NOT NULL,
MUSTERICINSIYET VARCHAR(1) NOT NULL,
MUSTERITELEFON VARCHAR(11) NOT NULL,
MUSTERIADRES INT,
PRIMARY KEY CLUSTERED
(
MUSTERIID ASC
)
WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY]
)ON [PRIMARY]



/*-------------------------------------------------FOREIGN KEY--------------------------------------------------------*/

ALTER TABLE ADRES WITH CHECK ADD CONSTRAINT [FK_ADRESMUSTERI] FOREIGN KEY(MUSTERIID) REFERENCES MUSTERILER (MUSTERIID) 
ALTER TABLE ADRES CHECK CONSTRAINT [FK_ADRESMUSTERI]

ALTER TABLE SIPARIS WITH CHECK ADD CONSTRAINT [FK_SIPARISMUSTERI] FOREIGN KEY(MUSTERIID) REFERENCES MUSTERILER (MUSTERIID)
ALTER TABLE SIPARIS CHECK CONSTRAINT [FK_SIPARISMUSTERI]

ALTER TABLE SIPARIS WITH CHECK ADD CONSTRAINT [FK_SIPARISSATICI] FOREIGN KEY(SATICIID) REFERENCES SATICI(SATICIID)
ALTER TABLE SIPARIS CHECK CONSTRAINT [FK_SIPARISSATICI]

ALTER TABLE SIPARIS WITH CHECK ADD CONSTRAINT [FK_SIPARISURUN] FOREIGN KEY(URUNID) REFERENCES URUN(URUNID)
ALTER TABLE SIPARIS CHECK CONSTRAINT [FK_SIPARISURUN]

/*-------------------------------------------------FOREIGN KEY--------------------------------------------------------*/





/**/

SELECT * FROM MUSTERILER

INSERT INTO MUSTERILER(MUSTERIAD,MUSTERISOYAD,MUSTERICINSIYET,MUSTERITELEFON)VALUES ('AHMET','KAVUS','E','5326151745')
INSERT INTO MUSTERILER(MUSTERIAD,MUSTERISOYAD,MUSTERICINSIYET,MUSTERITELEFON)VALUES ('SEFA','KALYA','E','5326151544')
INSERT INTO MUSTERILER(MUSTERIAD,MUSTERISOYAD,MUSTERICINSIYET,MUSTERITELEFON)VALUES ('SERDAR','KAVUS','E','5326856974')
INSERT INTO MUSTERILER(MUSTERIAD,MUSTERISOYAD,MUSTERICINSIYET,MUSTERITELEFON)VALUES ('EMRAH','KAVUS','E','5326568445')
INSERT INTO MUSTERILER(MUSTERIAD,MUSTERISOYAD,MUSTERICINSIYET,MUSTERITELEFON)VALUES ('EDA','GULER','K','5326158854')
INSERT INTO MUSTERILER(MUSTERIAD,MUSTERISOYAD,MUSTERICINSIYET,MUSTERITELEFON,MUSTERIADRES)VALUES ('EDA','GULER','K','5326158854',3)




SELECT * FROM ADRES

INSERT INTO ADRES(MusterıID,ADRESULKE,ADRESIL,ADRESILCE,ADRESYORUM) VALUES (1,'TURKIYE','ISTANBUL','PENDIK','EV ADRESI')
INSERT INTO ADRES(MusterıID,ADRESULKE,ADRESIL,ADRESILCE,ADRESYORUM) VALUES (1,'TURKIYE','ISTANBUL','TUZLA','IS ADRESI')
INSERT INTO ADRES(MusterıID,ADRESULKE,ADRESIL,ADRESILCE,ADRESYORUM) VALUES (2,'TURKIYE','IZMIR','KORDON','EV ADRESI')
INSERT INTO ADRES(MusterıID,ADRESULKE,ADRESIL,ADRESILCE,ADRESYORUM) VALUES (3,'TURKIYE','ÇORUM','OSMANCIK','IS ADRESI')
INSERT INTO ADRES(MusterıID,ADRESULKE,ADRESIL,ADRESILCE,ADRESYORUM) VALUES (4,'TURKIYE','ERZINCAN','MERKEZ','EV ADRESI')
INSERT INTO ADRES(MusterıID,ADRESULKE,ADRESIL,ADRESILCE,ADRESYORUM) VALUES (5,'TURKIYE','TRAPZON','SURMENE','EV ADRESI')
INSERT INTO ADRES(MusterıID,ADRESULKE,ADRESIL,ADRESILCE,ADRESYORUM) VALUES (5,'AMERIKA','PENSILVANYA','PITTSBURG','IS ADRESI')


SELECT * FROM SATICI

INSERT INTO SATICI(SATICIADI,SATICISOYADI,SATICITELEFON) VALUES ('MUSLUM','GURSES','5437645589')
INSERT INTO SATICI(SATICIADI,SATICISOYADI,SATICITELEFON) VALUES ('IBRAHIM','TATLISES','2164567894')
INSERT INTO SATICI(SATICIADI,SATICISOYADI,SATICITELEFON) VALUES ('ZEKI','MUREN','123456789')
INSERT INTO SATICI(SATICIADI,SATICISOYADI,SATICITELEFON) VALUES ('MUHAMMED','ARSLAN','42315648')
INSERT INTO SATICI(SATICIADI,SATICISOYADI,SATICITELEFON) VALUES ('ORHAN','ADNAN','5469875326')

SELECT * FROM URUN

INSERT INTO URUN(URUNKODU,URUNADI,URUNFİYATI) VALUES ('456','BUZDOLABI','788')
INSERT INTO URUN(URUNKODU,URUNADI,URUNFİYATI) VALUES ('8546','TELEFON','1500')
INSERT INTO URUN(URUNKODU,URUNADI,URUNFİYATI) VALUES ('36987','KLIMA','999')
INSERT INTO URUN(URUNKODU,URUNADI,URUNFİYATI) VALUES ('2233','CAMASIR MAKINASI','659')
INSERT INTO URUN(URUNKODU,URUNADI,URUNFİYATI) VALUES ('2369','BULASIK MAKINASI','3900')


ALTER TABLE SIPARIS ALTER COLUMN SIPARISTARIH VARCHAR(20)

SELECT * FROM SIPARIS

INSERT INTO SIPARIS(MUSTERIID,SIPARISTARIH,SIPARISDURUM,URUNID,SATICIID) VALUES (2,'17_08_2020','KARGODA',3,5)
INSERT INTO SIPARIS(MUSTERIID,SIPARISTARIH,SIPARISDURUM,URUNID,SATICIID) VALUES (1,'15_10_2020','KARGODA',4,1)
INSERT INTO SIPARIS(MUSTERIID,SIPARISTARIH,SIPARISDURUM,URUNID,SATICIID) VALUES (4,'17_08_2020','KARGODA',1,2)
INSERT INTO SIPARIS(MUSTERIID,SIPARISTARIH,SIPARISDURUM,URUNID,SATICIID) VALUES (1,'17_08_2020','KARGODA',2,1)
INSERT INTO SIPARIS(MUSTERIID,SIPARISTARIH,SIPARISDURUM,URUNID,SATICIID) VALUES (3,'17_08_2020','KARGODA',5,3)



/*
DROP TABLE SIPARIS
DELETE FROM SIPARIS
TRUNCATE TABLE SIPARIS
UPDATE MUSTERILER SET MUSTERICINSIYET='K' WHERE MUSTERIAD='SERDAR'
*/



SELECT DISTINCT MUSTERILER.MUSTERIAD+' '+MUSTERILER.MUSTERISOYAD [AD SOYAD], 
ADRES.ADRESULKE+' '+ADRES.ADRESIL+' '+ADRES.ADRESILCE+' '+ADRES.ADRESYORUM [AÇIK ADRES],
URUN.URUNADI [SİPARİŞ EDİLEN ÜRÜN], SIPARIS.SIPARISTARIH [SİPARİŞ TARİHİ], SIPARIS.SIPARISDURUM [ÜRÜN DURUMU], SATICI.SATICIADI+' '+SATICI.SATICISOYADI [ÜRÜN SATICISI] FROM MUSTERILER 
INNER JOIN SIPARIS ON MUSTERILER.MUSTERIID = SIPARIS.MUSTERIID
INNER JOIN ADRES ON ADRES.MusterıID=MUSTERILER.MUSTERIID
INNER JOIN URUN ON URUN.URUNID=SIPARIS.URUNID
INNER JOIN SATICI ON SATICI.SATICIID=SIPARIS.SATICIID





/*Madde2 */
Create procedure kuyt

as
begin
set nocount on;
select * from MUSTERILER
inner join ADRES on MUSTERILER.MUSTERIADRES = ADRES.MusterıID
end

exec kuyt
/*Madde2 */

select*from MUSTERILER

/*------------------Bundan her tablo için yapıp birer kayıt eklenecek madde1*/

create procedure MUSTERILERTABLOSUVERIEKLEME
(
@MUSTERIAD VARCHAR(20),
@MUSTERISOYAD varchar(20),
@MUSTERICINSIYET VARCHAR(1),
@MUSTERITELEFON VARCHAR(11),
@MUSTERIADRES INTEGER
)
as
insert into MUSTERILER values(@MUSTERIAD,@MUSTERISOYAD,@MUSTERICINSIYET,@MUSTERITELEFON,@MUSTERIADRES)

exec MUSTERILERTABLOSUVERIEKLEME 'DILARA','SEVEN','K','5556667788',N'2'
exec MUSTERILERTABLOSUVERIEKLEME 'ELIF','KALAYCI','K','4448667788',N'3'

select * from MUSTERILER


create procedure SATICITABLOSUNAVERIEKLEME
(
@SATICIADI VARCHAR(20),
@SATICISOYADI varchar(20),
@MDSTICITELEFON VARCHAR(11)
)
as
insert into SATICI values(@SATICIADI,@SATICISOYADI,@MDSTICITELEFON)

exec SATICITABLOSUNAVERIEKLEME 'CEMRE','URAL','7894561230'

select * from SATICI




create procedure SIPARISTABLOSUNAVERIEKLEME
(
@MUSTERIID INTEGER,
@SIPARISTARIH varchar(10),
@SIPARISDURUM VARCHAR(20),
@URUNID INTEGER,
@SATICIID INTEGER
)
as
insert into SIPARIS values(@MUSTERIID,@SIPARISTARIH,@SIPARISDURUM,@URUNID,@SATICIID)

exec SIPARISTABLOSUNAVERIEKLEME N'2','22/03/2022','KARGODA','3','4'

select * from SIPARIS



create procedure URUNEKLEME
(
@URUNKODU VARCHAR(20),
@URUNADI varchar(20),
@URUNFIYATI MONEY
)
as
insert into URUN values(@URUNKODU,@URUNADI,@URUNFIYATI)

exec URUNEKLEME 'KES605','KENDAL AMPUL',N'14'

select * from URUN









/*------------------Bundan her tablo için yapıp birer kayıt eklenecek madde1*/





CREATE PROCEDURE  elif
  AS
  BEGIN
  SET NOCOUNT ON;
  SELECT * FROM SIPARIS
  LEFT JOIN MUSTERILER ON SIPARIS.MUSTERIID = MUSTERILER.MUSTERIID

  END

  exec elif



  
CREATE INDEX diyafon
ON ADRES(ADRESULKE);





CREATE NONCLUSTERED INDEX URUNLERLAR ON URUN (URUNKODU ASC, URUNFİYATI DESC)






ALTER INDEX ALL ON SATICI REBUILD;
GO






ALTER INDEX diyafon ON ADRES REORGANIZE;
GO




ALTER INDEX URUNLERLAR ON URUN REBUILD;
GO

